### ISSUE TITLE
RTT calculation is error when transport without outgoing stream

### ISSUE THREAD

**Issue by vvspacetime** [medooze/media-server#79]
![image](https://user-images.githubusercontent.com/20473768/65763145-4ce42280-e155-11e9-9e31-ea75ca849ad4.png)

The data is got from medooze-media-node/IncomingStreamTrack.js/getStats.
First I set network to 30% loss rate, the rtt is high. After, when I cancel the loss rate setting, the rtt is recover to reasonable level.

Test Environment: company LAN，two computer

I have read your code, and I think the method which use NACK to detect the rtt is invalid when the network has some loss rate. But I don't know why and how to solve it.

**Comment by murillo128** [comment]
umm.. yes and no..

The rtt rtx based calculation only happens if there is no outgoing stream, as the rtcp rtt is received on the Receiver Report, which won't happen if no outgoing streams are in use:
https://github.com/medooze/media-server/blob/ac00c374b2db2d094aca2c69d179d6a7bf820458/src/DTLSICETransport.cpp#L507

For calculating the rtt and the rtx, I request a dummy rtx on a received packet, so I can calculate the rrt between the nack and receiving it again.

I assume that libwebrtc  throttles the RTX if you are using such high packet loss, so the rtx packet to calculate the delay increases.

Note that in this case, the stream rtt in fact reflects the actual rtt as I use the rtt for tuning the RTX code.

**Comment by vvspacetime** [comment]
OK, I understand it. Thank you!

**Comment by murillo128** [comment]
Anyway, thank you for the report, I was not aware of libwebrtc behavior!
